flip_status_indicators = true
volnorm = true
notify = true
gapless = true

[theme]
primary = "light white"
secondary = "light black"
title = "red"
playing = "red"
playing_bg = "black"
highlight = "light white"
highlight_bg = "red"
error = "light white"
error_bg = "red"
statusbar = "black"
statusbar_progress = "red"
statusbar_bg = "red"
cmdline = "light white"
cmdline_bg = "black"
