flip_status_indicators = true
volnorm = true
notify = true
gapless = true

[theme]
primary = "white"
secondary = "black"
title = "#009900"
playing = "#009900"
playing_bg = "black"
highlight = "light white"
highlight_bg = "#009900"
error = "light white"
error_bg = "#009900"
statusbar = "black"
statusbar_progress = "#009900"
statusbar_bg = "#009900"
cmdline = "light white"
cmdline_bg = "black"
