## All this options are overriden by the command line.
## So check your ksmcon launch script if an option has no visible effect
##
## For boolean options (like hwaccel), you can disable
## them by adding a "no-" prefix, like no-hwaccel or no-mouse

## Use drm driver (enabled by default)
drm

## GPU to use
gpus=all

## Enable 3d rendering
hwaccel

## Fonts
font-size=18
font-name=Monaspace Neon, WenQuanYi Micro Hei Mono

## Enable mouse
no-mouse

## Colors palette
palette=base16-dark
