#          __                  __    _             __  ___________
#    _____/ /_____ ___________/ /_  (_)___        / /_<  / __/ __ \
#   / ___/ __/ __ `/ ___/ ___/ __ \/ / __ \______/ //_/ / /_/ / / /
#  (__  ) /_/ /_/ / /  (__  ) / / / / /_/ /_____/ ,< / / __/ /_/ /
# /____/\__/\__,_/_/  /____/_/ /_/_/ .___/     /_/|_/_/_/  \____/
#                                 /_/

add_newline = false

format = """$cmd_duration\
$python\
$directory\
$git_branch\
$character"""

[character]
format = "$symbol "
success_symbol = "[❯](bold #ffffff)"
error_symbol = "[❯](bold #ffffff)"

[directory]
style = "italic bold"
home_symbol = "~"
read_only = ""
truncation_length = 2
truncation_symbol = '../'

[cmd_duration]
format = "\n[$duration]($style)\n"
style = "italic bold"
show_milliseconds = false

[git_branch]
style = "italic bold"

[python]
format = '(\($virtualenv\) )'
