#!/usr/bin/env bash

# Taken from here:
# https://wiki.archlinux.org/title/Wine#Unregister_existing_Wine_file_associations

# "bash strict mode"
set -uo pipefail

# run su check
if [ "$(/usr/bin/grep -c "sudo" "$(which "${0}")")" -gt 1 ]; then
    printf "[\e[1m\e[91m!\e[0m]%s\n" " Contains root commands"
    sleep 1
fi

# dont run as root
if [ $EUID -eq 0 ]; then
    printf "[\e[1m\e[91m✗\e[0m]%s\n" " Run as user"
fi

# unregister existing Wine file associations
printf "[\e[1m\e[93m⧗\e[0m]%s\n" " Unregistering existing Associations.."
rm -f ~/.local/share/applications/wine-extension*.desktop
rm -f ~/.local/share/icons/hicolor/*/*/application-x-wine-extension*

# remove cache
printf "[\e[1m\e[93m⧗\e[0m]%s\n" " Removing Cache.."
rm -f ~/.local/share/applications/mimeinfo.cache
rm -f ~/.local/share/mime/packages/x-wine*
rm -f ~/.local/share/mime/application/x-wine-extension*

# update cache
printf "[\e[1m\e[93m⧗\e[0m]%s\n" " Updating Cache.."
update-desktop-database ~/.local/share/applications
update-mime-database ~/.local/share/mime/

# we're done
printf "[\e[1m\e[92m✓\e[0m]%s\n" " Done"
