#!/usr/bin/env bash

# "bash strict mode"
set -uo pipefail

# dont run as root
if [ "$EUID" -eq 0 ]; then
    printf "[\e[1m\e[91m✗\e[0m]%s\n" " run as user!"
fi

# check if jq is available
if ! command -v jq >> /dev/null; then
    printf "[\e[1m\e[91m✗\e[0m]%s\n" " needs 'jq' installed!"
fi

# config file paths
ROFI_CONF_FILE="/home/${USER}/.config/rofi/config.rasi.d/user.rasi"
HYPRLAND_CONF_FILE="/home/${USER}/.config/hypr/hyprland.conf.d/user.conf"
DUNST_CONF_FILE="/home/${USER}/.config/dunst/dunstrc.d/user.conf"
EWW_CONF_FILE="/home/${USER}/.config/eww/eww.scss.d/user.scss"
KITTY_CONF_FILE="/home/${USER}/.config/kitty/kitty.conf.d/user.conf"

# get colors
COLOR_SCHEME=$(cat "/home/${USER}/.cache/rwpspread/rwps_colors.json")
RWP_FG=$(echo ${COLOR_SCHEME} | jq '.material.dark.onbackground' | tr -d '"#')
RWP_BG=$(echo ${COLOR_SCHEME} | jq '.material.dark.background' | tr -d '"#')
RWP_ACT=$(echo ${COLOR_SCHEME} | jq '.material.dark.primary' | tr -d '"#')
RWP_NRM=$(echo ${COLOR_SCHEME} | jq '.material.dark.inverseprimary' | tr -d '"#')
RWP_BRD=$(echo ${COLOR_SCHEME} | jq '.material.dark.outline' | tr -d '"#')

# rofi
CNF_FILE="${ROFI_CONF_FILE}"
sed -i -r \
's/^.*ACT:.*;/\tACT:\t#'"$RWP_ACT"';/' \
"$CNF_FILE"
sed -i -r \
's/^.*NRM:.*;/\tNRM:\t#'"$RWP_NRM"';/' \
"$CNF_FILE"
sed -i -r \
's/^.*FG:.*;/\tFG:\t#'"$RWP_FG"';/' \
"$CNF_FILE"
sed -i -r \
's/^.*BG:.*;/\tBG:\t#'"$RWP_BG"';/' \
"$CNF_FILE"
sed -i -r \
's/^.*BGOPQ:.*;/\tBGOPQ:\t#'"$RWP_BG"'EE;/' \
"$CNF_FILE"

# hyprland
CNF_FILE="${HYPRLAND_CONF_FILE}"
sed -i -r \
's/^\$FGD.*/$FGD=0xFF'"$RWP_FG"'/' \
"$CNF_FILE"
sed -i -r \
's/^\$BGD.*/$BGD=0xFF'"$RWP_BG"'/' \
"$CNF_FILE"
sed -i -r \
's/^\$NRM.*/$NRM=0xFF'"$RWP_NRM"'/' \
"$CNF_FILE"
sed -i -r \
's/^\$ACT.*/$ACT=0xFF'"$RWP_ACT"'/' \
"$CNF_FILE"
sed -i -r \
's/^\$BRD.*/$BRD=0xFF'"$RWP_BRD"'/' \
"$CNF_FILE"

# dunst
CNF_FILE="${DUNST_CONF_FILE}"
sed -i -r \
's/^\tforeground.*=.*/\tforeground = "#'"$RWP_FG"'"/' \
"$CNF_FILE"
sed -i -r \
's/^\tbackground.*=.*/\tbackground = "#'"$RWP_BG"'EE"/' \
"$CNF_FILE"
sed -i -r \
's/^\tframe_color.*=.*/\tframe_color = "#'"$RWP_BRD"'EE"/' \
"$CNF_FILE"
sed -i -r \
's/^\thighlight.*=.*/\thighlight = "#'"$RWP_ACT"'"/' \
"$CNF_FILE"

# eww
CNF_FILE="${EWW_CONF_FILE}"
sed -i -r \
's/^\$fg:.*;/$fg: #'"$RWP_FG"';/' \
"$CNF_FILE"
sed -i -r \
's/^\$bg:.*;/$bg: #'"$RWP_BG"';/' \
"$CNF_FILE"
sed -i -r \
's/^\$nrm:.*;/$nrm: #'"$RWP_NRM"';/' \
"$CNF_FILE"
sed -i -r \
's/^\$act:.*;/$act: #'"$RWP_ACT"';/' \
"$CNF_FILE"

# kitty
CNF_FILE="${KITTY_CONF_FILE}"
sed -i -r \
's/^background\s#.*$/background #'"$RWP_BG"'/' \
"$CNF_FILE"
sed -i -r \
's/^foreground\s#.*$/foreground #'"$RWP_FG"'/' \
"$CNF_FILE"

printf "[\e[1m\e[92m✓\e[0m]%s\n" " themed!"
