#!/usr/bin/env bash

# "bash strict mode"
set -uo pipefail

# run su check
if [ "$(/usr/bin/grep -c "sudo" "$(which "${0}")")" -gt 1 ]; then
    printf "[\e[1m\e[91m!\e[0m]%s\n" " Contains root commands"
    sleep 1
fi

# dont run as root
if [ $EUID -eq 0 ]; then
    printf "[\e[1m\e[91m✗\e[0m]%s\n" " Run as user"
fi

if [ $# -eq 0 ]; then
    printf "[\e[1m\e[91m✗\e[0m]%s\n" " specify a wallpaper"
else
    if file "$1" | /usr/bin/grep "image" > /dev/null; then
        TO_SET=$(readlink -f "${1}")
        ln -sf "${TO_SET}" "/home/${USER}/.wallpaper"
        printf "[\e[1m\e[92m✓\e[0m]%s\n" " Done"
        exit 0
    else
        printf "[\e[1m\e[91m✗\e[0m]%s\n" " ${1} is invalid"
        exit 1
    fi
fi
