#!/usr/bin/env bash

# "bash strict mode"
set -uo pipefail

# run su check
if [ "$(/usr/bin/grep -c "sudo" "$(which "${0}")")" -gt 1 ]; then
    printf "[\e[1m\e[91m!\e[0m]%s\n" " Contains root commands"
    sleep 1
fi

# dont run as root
if [ $EUID -eq 0 ]; then
    printf "[\e[1m\e[91m✗\e[0m]%s\n" " Run as user"
fi

# execute a command for each electron version
while IFS= read -r line; do
    # symlink to main electron flags file
    if ! [ -f "/home/${USER}/.config/${line%-bin}-flags.conf" ]; then
        /usr/bin/ln -s "/home/${USER}/.config/electron-flags.conf" "/home/${USER}/.config/${line%-bin}-flags.conf"
    fi
    printf "[\e[1m\e[92m✓\e[0m]%s\n" " ${line%-bin}-flags.conf → electron-flags.conf"
done < <(/usr/bin/pacman -Q | /bin/grep -e 'electron[0-9][0-9]' | /bin/awk '{print $1}')

exit 0
