#!/usr/bin/env bash

# "bash strict mode"
set -uo pipefail

# dont run as root
if [ $EUID -eq 0 ]; then
    printf "[\e[1m\e[91m✗\e[0m]%s\n" " Run as user"
    exit 1
fi

# run su check
if [ "$(/usr/bin/grep -c "sudo" "$(which "${0}")")" -gt 1 ]; then
    printf "[\e[1m\e[91m!\e[0m]%s\n" " Contains root commands"
    sleep 0.5
fi

GLOBAL_THEME_PATH="/usr/share"
USER_LOCAL_SHARE="/home/${USER}/.local/share"
USER_HOME="/home/${USER}"

# ensure home and alt path are available
printf "[\e[1m\e[93m⧗\e[0m]%s\n" " Checking folder availability.."
if [ ! -d "${USER_LOCAL_SHARE}/themes" ]; then
    printf "[\e[1m\e[93m⧗\e[0m]%s\n" " Creating ${USER_LOCAL_SHARE}/themes.."
    mkdir -p "${USER_LOCAL_SHARE}/themes"
fi
if [ ! -d "${USER_LOCAL_SHARE}/icons" ]; then
    printf "[\e[1m\e[93m⧗\e[0m]%s\n" " Creating ${USER_LOCAL_SHARE}/icons.."
    mkdir -p "${USER_LOCAL_SHARE}/icons"
fi
if [ ! -d "${USER_HOME}/.themes" ]; then
    printf "[\e[1m\e[93m⧗\e[0m]%s\n" " Creating ${USER_HOME}/.themes.."
    mkdir -p "${USER_HOME}/.themes"
fi
if [ ! -d "${USER_HOME}/.icons" ]; then
    printf "[\e[1m\e[93m⧗\e[0m]%s\n" " Creating ${USER_HOME}/.icons.."
    mkdir -p "${USER_HOME}/.icons"
fi
printf "[\e[1m\e[92m✓\e[0m]%s\n" " Folders OK"

# copy themes to home and alt location
NUM_THEMES=$(find "${GLOBAL_THEME_PATH}/themes/" -maxdepth 1 -mindepth 1 -type d | wc -l)
printf "[\e[1m\e[93m⧗\e[0m]%s\n" " Copying ${NUM_THEMES} current themes.."
sudo cp -ar "${GLOBAL_THEME_PATH}/themes/." "${USER_LOCAL_SHARE}/themes"
sudo cp -ar "${GLOBAL_THEME_PATH}/themes/." "${USER_HOME}/.themes"

# copy icons to home and alt location
NUM_ICONS=$(find "${GLOBAL_THEME_PATH}/icons/" -maxdepth 1 -mindepth 1 -type d | wc -l)
printf "[\e[1m\e[93m⧗\e[0m]%s\n" " Copying ${NUM_ICONS} current icons.."
sudo cp -ar "${GLOBAL_THEME_PATH}/icons/." "${USER_LOCAL_SHARE}/icons"
sudo cp -ar "${GLOBAL_THEME_PATH}/icons/." "${USER_HOME}/.icons"

# set permissions back to user
printf "[\e[1m\e[93m⧗\e[0m]%s\n" " Fixing permissions.."
sudo chown -R "${USER}":"${USER}" "${USER_LOCAL_SHARE}/themes"
sudo chown -R "${USER}":"${USER}" "${USER_LOCAL_SHARE}/icons"
sudo chown -R "${USER}":"${USER}" "${USER_HOME}/.themes"
sudo chown -R "${USER}":"${USER}" "${USER_HOME}/.icons"

printf "[\e[1m\e[92m✓\e[0m]%s\n" " Done"
exit 0
