add_newline = false

format = """
$python\
$rust\
$go\
$lua\
$java\
$php\
$git_branch\
$git_state\
$git_commit\
$directory\n\
$cmd_duration\
$character"""

[character]
format = "$symbol "
success_symbol = "[>](bold white)"
error_symbol = "[>](bold red)"

[directory]
style = "italic bold purple"
read_only = ""

[cmd_duration]
format = "took [$duration]($style)\n"
style = "bold green"
show_milliseconds = false