add_newline = false

format = """$python\
$cmd_duration\
$directory\
$git_branch\
$character"""

[character]
format = "$symbol "
success_symbol = "[❯](bold #ffffff)"
error_symbol = "[❯](bold #ffffff)"

[directory]
style = "italic bold #ffffff"
home_symbol = "~"
read_only = ""

[cmd_duration]
format = "\n[$duration]($style)\n"
style = "italic bold #66ff66"
show_milliseconds = false

[git_branch]
style = "italic bold #66ff66"

[python]
format = '(\($virtualenv\) )'