add_newline = false

format = """
$cmd_duration\
$python\
$rust\
$go\
$lua\
$java\
$php\
$git_branch\
$git_state\
$git_commit\
$directory\
$character"""

[character]
format = "$symbol "
success_symbol = "[>](bold #ffffff)"
error_symbol = "[>](bold #ff5555)"

[directory]
style = "italic bold #9e9e9e"
read_only = ""

[cmd_duration]
format = "\n[$duration]($style)\n"
style = "italic bold #66ff66"
show_milliseconds = false