add_newline = false

format = """
$cmd_duration\
$python\
$rust\
$go\
$lua\
$java\
$php\
$git_branch\
$git_state\
$git_commit\
$directory\
$character"""

[character]
format = "$symbol "
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"

[directory]
style = "italic bold white"
read_only = ""

[cmd_duration]
format = "\ntook [$duration]($style)\n"
style = "bold green"
show_milliseconds = false