#!/usr/bin/env bash

# "bash strict mode"
set -uo pipefail

# give user feedback
scriptFeedback() {
    case $1 in
        error)
            printf "[\e[1m\e[9%sm%s\e[0m]%s\n" "1" "✗" " $2"
            exit 1
            ;;
        success)
            printf "[\e[1m\e[9%sm%s\e[0m]%s\n" "2" "✓" " $2"
            ;;
    esac
}

# dont run as root
if [ "$EUID" -eq 0 ]; then
    scriptFeedback error "run as user!"
fi

# get colors
WAL_FG=$(cat .cache/wal/colors.json \
| jq '.special.foreground' \
| tr -d '"#' | tr '[:lower:]' '[:upper:]')
WAL_BG=$(cat .cache/wal/colors.json \
| jq '.special.background' \
| tr -d '"#' | tr '[:lower:]' '[:upper:]')
WAL_ACT=$(cat .cache/wal/colors.json \
| jq '.colors.color8' \
| tr -d '"#' | tr '[:lower:]' '[:upper:]')
WAL_NRM=$(cat .cache/wal/colors.json \
| jq '.colors.color1' \
| tr -d '"#' | tr '[:lower:]' '[:upper:]')

# rofi
CNF_FILE="/home/$USER/.config/rofi/colors.rasi"
sed -i -r \
's/^.*ACT:.*;/\tACT:\t\t\t#'"$WAL_ACT"';/' \
"$CNF_FILE"
sed -i -r \
's/^.*NRM:.*;/\tNRM:\t\t\t#'"$WAL_NRM"';/' \
"$CNF_FILE"
sed -i -r \
's/^.*FG:.*;/\tFG:\t\t\t\t#'"$WAL_FG"';/' \
"$CNF_FILE"
sed -i -r \
's/^.*BG:.*;/\tBG:\t\t\t\t#'"$WAL_BG"';/' \
"$CNF_FILE"
sed -i -r \
's/^.*OPQ_BG:.*;/\tOPQ-BG:\t\t\t#'"$WAL_BG"'EE;/' \
"$CNF_FILE"

# waybar
CNF_FILE="/home/$USER/.config/waybar/style.css"
sed -i -r \
's/^@define-color.*fg.*;/@define-color fg #'"$WAL_FG"';/' \
"$CNF_FILE"
sed -i -r \
's/^@define-color.*bg.*;/@define-color bg #'"$WAL_BG"';/' \
"$CNF_FILE"
sed -i -r \
's/^@define-color.*nrm.*;/@define-color nrm #'"$WAL_NRM"';/' \
"$CNF_FILE"
sed -i -r \
's/^@define-color.*act.*;/@define-color act #'"$WAL_ACT"';/' \
"$CNF_FILE"

# hyprland
CNF_FILE="/home/$USER/.config/hypr/colors.conf"
sed -i -r \
's/^\$FGD.*/$FGD=0xFF'"$WAL_FG"'/' \
"$CNF_FILE"
sed -i -r \
's/^\$BGD.*/$BGD=0xFF'"$WAL_BG"'/' \
"$CNF_FILE"
sed -i -r \
's/^\$NRM.*/$NRM=0xFF'"$WAL_NRM"'/' \
"$CNF_FILE"
sed -i -r \
's/^\$ACT.*/$ACT=0xFF'"$WAL_ACT"'/' \
"$CNF_FILE"

# dunst
CNF_FILE="/home/$USER/.config/dunst/dunstrc"
sed -i -r \
's/^\tforeground.*=.*/\tforeground = "#'"$WAL_FG"'"/' \
"$CNF_FILE"
sed -i -r \
's/^\tbackground.*=.*/\tbackground = "#'"$WAL_BG"'EE"/' \
"$CNF_FILE"
sed -i -r \
's/^\tframe_color.*=.*/\tframe_color = "#'"$WAL_ACT"'"/' \
"$CNF_FILE"
sed -i -r \
's/^\thighlight.*=.*/\thighlight = "#'"$WAL_NRM"'"/' \
"$CNF_FILE"

# eww
CNF_FILE="/home/$USER/.config/eww/colors.scss"
sed -i -r \
's/^\$fg:.*;/$fg: #'"$WAL_FG"';/' \
"$CNF_FILE"
sed -i -r \
's/^\$bg:.*;/$bg: #'"$WAL_BG"';/' \
"$CNF_FILE"
sed -i -r \
's/^\$nrm:.*;/$nrm: #'"$WAL_NRM"';/' \
"$CNF_FILE"
sed -i -r \
's/^\$act:.*;/$act: #'"$WAL_ACT"';/' \
"$CNF_FILE"

scriptFeedback success "'themed!"
