#!/usr/bin/env bash

#░█░█░█░░░█░█░█▄█░░░░░█▀▀░█▀█░█▀█░█▀▀░▀█▀░█▀▀░░░░░█░█░▀█░░█▀▀░▄▀▄
#░█▀█░█░░░█▄█░█░█░▄▄▄░█░░░█░█░█░█░█▀▀░░█░░█░█░▄▄▄░█▀▄░░█░░█▀▀░█/█
#░▀░▀░▀▀▀░▀░▀░▀░▀░░░░░▀▀▀░▀▀▀░▀░▀░▀░░░▀▀▀░▀▀▀░░░░░▀░▀░▀▀▀░▀░░░░▀░

hc() {
    herbstclient "$@"
}

hc emit_hook reload

#configure monitors
~/.config/herbstluftwm/scripts/xrandrapply.sh &

# remove all existing keybindings
hc keyunbind --all

# Use the super key as the main modifier
Mod=Mod4

# modifying clients
hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-c close

# spawning things
hc keybind $Mod-Return spawn kitty
hc keybind $Mod-a spawn rofi -show run
hc keybind $Mod-Shift-a spawn rofi -show calc
hc keybind $Mod-Shift-w spawn rofi -show window
hc keybind $Mod-l spawn ~/.config/herbstluftwm/scripts/i3lock.sh
hc keybind $Mod-q spawn nemo
hc keybind $Mod-Shift-s spawn ~/.config/herbstluftwm/scripts/takeScreenshot.sh

# function keys
hc keybind XF86AudioRaiseVolume spawn ~/.config/herbstluftwm/scripts/volumeUp.sh
hc keybind XF86AudioLowerVolume spawn ~/.config/herbstluftwm/scripts/volumeDown.sh
hc keybind XF86AudioNext spawn playerctl next
hc keybind XF86AudioPrev spawn playerctl previous
hc keybind XF86AudioPlay spawn playerctl play-pause

# focusing clients
hc keybind $Mod-Left  		focus left
hc keybind $Mod-Down  		focus down
hc keybind $Mod-Up    		focus up
hc keybind $Mod-Right 		focus right
hc keybind $Mod-Shift-j     	focus down
hc keybind $Mod-Shift-k     	focus up
hc keybind $Mod-Shift-h     	focus left
hc keybind $Mod-Shift-l	        focus right

# moving clients
hc keybind $Mod-Shift-Down  	shift down
hc keybind $Mod-Shift-Up    	shift up
hc keybind $Mod-Shift-Left     	shift left
hc keybind $Mod-Shift-Right     shift right
hc keybind $Mod-Shift-j     	shift down
hc keybind $Mod-Shift-k     	shift up
hc keybind $Mod-Shift-h     	shift left
hc keybind $Mod-Shift-l	        shift right

# splitting frames
hc keybind $Mod-u       split   bottom  0.5
hc keybind $Mod-o       split   top     0.5

# explode into subframes
hc keybind $Mod-Control-space split explode

# tags
tag_names=( I II III IV V )
tag_keys=( {1..5} 0 )

# set default frame layout
hc set default_frame_layout grid

# create workspaces
hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# set default layout for tags
for i in 0 1 2 3 4 ; do
  #set vetical layout for first frame
  if [ "$i" == 0 ]; then
    hc use_index "$i"
    hc set_layout vertical
  fi
done

# cycle through tags
hc keybind $Mod-Tab use_index +1 --skip-visible
hc keybind $Mod-Shift-Tab  use_index -1 --skip-visible

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1

# unbind all mouse keys
hc mouseunbind --all

# modifying floating clients
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# set multi monitor focus
hc set focus_crosses_monitor_boundaries true

# focus follows mouse
hc set focus_follows_mouse true

# dont swap monitors to get tag
hc set swap_monitors_to_get_tag false

# colors
colorNormal='#384048'
colorActive='#b0b0c8'
colorUrgent='#ffffff'

# theme / behaviour
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc attr theme.active.color "$colorActive"
hc attr theme.normal.color "$colorNormal"
hc attr theme.urgent.color "$colorUrgent"
hc attr theme.border_width 2
hc attr theme.floating.border_width 2
hc attr theme.floating.active.color "$colorActive"
hc attr theme.floating.normal.color "$colorNormal"
hc attr theme.active.inner_color '$colorActive'
hc attr theme.active.outer_color '$colorNormal'
hc set window_gap 14
hc set frame_padding on
hc set smart_window_surroundings off
hc set smart_frame_surroundings on
hc set mouse_recenter_gap 10
hc set frame_border_width 0
hc set frame_active_opacity 0
hc set frame_normal_opacity 0
hc set always_show_frame off
hc set frame_gap 0

# rules
hc unrule -F

# focus new clients
hc rule focus=on
hc rule floatplacement=smart
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

# unlock
hc unlock

# detect monitors
hc detect_monitors

# numlock
numlockx &

# start compton
picom -b --experimental-backends &

# start polybars
~/.config/polybar/startbars-hlwm.sh

# start dunst
killall -q dunst
dunst &

# restore wallpapers
nitrogen --restore &
