#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

#exports
export LANG=en_US.UTF-8
export TERM="xterm-256color"

#archive extraction
ex ()
{
  if [ -f $1 ] ; then
    case $1 in
      *.tar.bz2)   tar xjf $1   ;;
      *.tar.gz)    tar xzf $1   ;;
      *.bz2)       bunzip2 $1   ;;
      *.rar)       unrar x $1   ;;
      *.gz)        gunzip $1    ;;
      *.tar)       tar xf $1    ;;
      *.tbz2)      tar xjf $1   ;;
      *.tgz)       tar xzf $1   ;;
      *.zip)       unzip $1     ;;
      *.Z)         uncompress $1;;
      *.7z)        7z x $1      ;;
      *.deb)       ar x $1      ;;
      *.tar.xz)    tar xf $1    ;;
      *.tar.zst)   unzstd $1    ;;      
      *)           echo "'$1' cannot be extracted via ex()" ;;
    esac
  else
    echo "'$1' is not a valid file"
  fi
}

#shortcut for neovide
alias nv="neovide"

#use new rust programs for these commands (req procs, exa, bat)
alias ps="procs"
alias ls="exa -l"
alias cat="bat"

#put system to sleep
alias suspendsystem="systemctl suspend && betterlockscreen -l"

#get fastest mirrors
alias mirror="sudo reflector -f 30 -l 30 --number 15 --verbose --save /etc/pacman.d/mirrorlist"

#start ssh agent and add keys
alias startssh='eval `ssh-agent -s` && ssh-add ~/git/.keystore/github_rsa'

#remove orphans
alias cleanup='sudo pacman -Rs $(pacman -Qtdq)'

#clear pacman cache
alias cacheclean='paru -Scc'

#update AUR packages
alias aurup='paru -a -Syu'

#clear pacman cache noconfirm
alias hardcacheclean='sudo paru -Scc --noconfirm'

#typos
alias yay="paru"
alias pdw="pwd"
alias sl="ls"

#prompt
PS1='┌─[\u@\h]─[\W]─[\A]\n└─> '

#custom start thingies
echo
PF_INFO="ascii title os kernel pkgs uptime wm " /usr/bin/pfetch 
