#          __                _ __  __              __  ___________ 
#   ____ _/ /___ ___________(_) /_/ /___  __      / /_<  / __/ __ \
#  / __ `/ / __ `/ ___/ ___/ / __/ __/ / / /_____/ //_/ / /_/ / / /
# / /_/ / / /_/ / /__/ /  / / /_/ /_/ /_/ /_____/ ,< / / __/ /_/ / 
# \__,_/_/\__,_/\___/_/  /_/\__/\__/\__, /     /_/|_/_/_/  \____/  
#                                  /____/                          
# 

import = [ "~/.config/alacritty/alacritty-colors.toml" ]
ipc_socket = false

[font]
size = 15.0

[font.bold]
family = "Monaspace Neon"
style = "Bold"

[font.bold_italic]
family = "Monaspace Neon"
style = "Bold Italic"

[font.italic]
family = "Monaspace Neon"
style = "Italic"

[font.normal]
family = "Monaspace Neon"
style = "Medium"

[window]
padding = { x = 8, y = 8 }
opacity = 0.93

[cursor]
style = { shape = "Underline", blinking = "On" }
blink_interval = 400
